-- =============================================================================================
-- seed.sql — GENERATED FILE, DO NOT EDIT BY HAND
--
-- Source of truth: src/lib/quiz/seed-questions.ts and src/lib/config/constants.ts
-- Regenerate with:  npm run seed:sql
--
-- Run this after 0001_schema.sql and 0002_functions.sql.
-- It is safe to run more than once: settings are upserted and questions are matched on their code.
--
-- REVIEW NOTE: all 120 questions are seeded active and 'approved' so the bank is servable straight
-- away. Read them in /admin/questions before the event and edit anything you want to reword.
-- =============================================================================================

-- ---------------------------------------------------------------------------------------------
-- Event settings (single row)
-- ---------------------------------------------------------------------------------------------

insert into app_settings (
  id, quiz_title, hook_text, supporting_line, event_name, event_location,
  event_start_at, event_end_at, winner_announcement_at, quiz_state,
  quiz_duration_seconds, questions_per_attempt, leaderboard_size,
  result_auto_reset_seconds, leaderboard_refresh_seconds,
  prize_first, prize_second, prize_third, spin_cta_text, qr_caption,
  privacy_contact_text, privacy_notice_text, rules_text
) values (
  'singleton',
  'The AI Leadership Challenge',
  'Can you make the right AI decisions under pressure?',
  '7 leadership decisions. 130 seconds. One live leaderboard.',
  'People Matters TechHR Summit 2026',
  'Delhi, India',
  '2026-08-06T09:00:00+05:30'::timestamptz,
  '2026-08-07T18:00:00+05:30'::timestamptz,
  '2026-08-07T17:00:00+05:30'::timestamptz,
  'active',
  130,
  7,
  5,
  40,
  10,
  'iPad + Custom AI Session + Hamper',
  'Custom AI Session + Hamper',
  'Hamper',
  'Ask the team about your spin of the wheel.',
  'Scan to take the challenge',
  'Speak to any Outskill team member at the booth, or use the contact address printed on your event pass.',
  'We collect your name, email address and phone number so we can run the challenge, place you on the leaderboard and verify prize winners.

Your name appears on the public leaderboard only if you tick the leaderboard opt-in. Otherwise you appear as an anonymous leader.

We only send follow-up resources if you tick the marketing opt-in, which is separate and optional. Giving us your email address does not on its own sign you up for anything. You can ask us to stop at any time.

We do not send quiz-result emails. Your score and answer review appear on the tablet immediately after you submit, and only there.

We never publish your email address or phone number. They are used to verify prize winners and, where you have opted in, to send follow-up.

Your details are kept for seven days after the event, after which the Outskill team anonymises them once the lead export is complete.',
  'One entry per person. Each email address and each phone number may complete the challenge once.

You have 130 seconds to answer 7 workplace AI decisions. Accuracy determines your score; speed breaks a tie.

Once you select an answer you cannot return to the previous question. Unanswered questions count as incorrect.

Ranking order is: more correct answers first, then a faster completion time, then an earlier submission.

Entries in the top 5 must be verified in person at the Outskill desk. Bring your event badge.

Your result and an answer review appear on the tablet straight after you submit. We do not email results.

This is a seven-question challenge for the booth, not a scientific assessment of you or your organisation.

Outskill may disqualify any entry that shows evidence of automation, impersonation or duplicate registration.

The winner is the highest-ranked verified, non-disqualified entry once the Outskill team locks the challenge.

The decision of the Outskill team on verification, disqualification and prize allocation is final.'
)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------------------------
-- Question bank — 120 questions
-- ---------------------------------------------------------------------------------------------

insert into questions (
  code, pillar, difficulty, question_text, options, correct_option_id, explanation, active, review_status
) values
  ('BJ-01', 'business_judgment', 'easy', 'Three functions each want to run their own AI pilot next quarter. What is the strongest first move?', '[{"id":"a","text":"Agree the business outcome each pilot must move"},{"id":"b","text":"Pick the function with the largest budget"},{"id":"c","text":"Delay everything until a strategy is written"},{"id":"d","text":"Approve all three so no function feels deprioritised"}]'::jsonb, 'a', 'Pilots without an agreed outcome measure cannot be compared, scaled or stopped. Defining the target metric first costs days and saves quarters.', true, 'approved'),
  ('BJ-02', 'business_judgment', 'easy', 'A vendor demo shows an impressive AI result on their sample data. What should you ask for next?', '[{"id":"a","text":"A longer demo with more features"},{"id":"b","text":"A trial on your own messy data"},{"id":"c","text":"A list of their largest clients"},{"id":"d","text":"A discount for signing this quarter"}]'::jsonb, 'b', 'Vendor demos run on curated data. The only meaningful test is performance on your real, incomplete, inconsistent records.', true, 'approved'),
  ('BJ-03', 'business_judgment', 'easy', 'Your AI pilot saved 400 hours but headcount and cost are unchanged. How should you report it?', '[{"id":"a","text":"Report it as a productivity breakthrough for the function"},{"id":"b","text":"Report the hours as cost savings"},{"id":"c","text":"Report hours freed and where they were redeployed"},{"id":"d","text":"Delay reporting until savings appear"}]'::jsonb, 'c', 'Time freed only becomes value when it is redeployed. Reporting hours as money not yet saved erodes credibility with the CFO.', true, 'approved'),
  ('BJ-04', 'business_judgment', 'easy', 'Which use case is usually the strongest candidate for a first enterprise AI deployment?', '[{"id":"a","text":"Rare, high-stakes, board-visible decisions"},{"id":"b","text":"The use case a competitor announced"},{"id":"c","text":"The most technically interesting problem"},{"id":"d","text":"High volume, repetitive, tolerant of review"}]'::jsonb, 'd', 'Frequency creates measurable value quickly and human review contains the downside. Rare high-stakes decisions offer neither.', true, 'approved'),
  ('BJ-05', 'business_judgment', 'medium', 'An AI tool costs ₹40 lakh a year and saves 2% of one team''s time. The team asks to renew. What do you do?', '[{"id":"a","text":"Compare the spend against alternative uses"},{"id":"b","text":"Cancel, since 2% is too small"},{"id":"c","text":"Renew, since the team says the tool is working well"},{"id":"d","text":"Renew at a reduced seat count"}]'::jsonb, 'a', 'Neither enthusiasm nor a small percentage settles the question. The decision is whether that budget buys more value elsewhere.', true, 'approved'),
  ('BJ-06', 'business_judgment', 'medium', 'Your AI forecasting model is 92% accurate. The business wants to automate ordering. What matters most?', '[{"id":"a","text":"Raising accuracy to 95% first"},{"id":"b","text":"The cost of the 8% of errors"},{"id":"c","text":"How the model compares to competitors"},{"id":"d","text":"Whether the vendor guarantees accuracy"}]'::jsonb, 'b', 'Accuracy is meaningless without the cost of being wrong. An 8% error rate is trivial in one context and unacceptable in another.', true, 'approved'),
  ('BJ-07', 'business_judgment', 'medium', 'A successful six-month AI pilot is ready to scale. What most often causes scaling to fail?', '[{"id":"a","text":"The model degrading at higher volume"},{"id":"b","text":"Insufficient computing capacity for the larger volume"},{"id":"c","text":"Process, data and ownership outside the pilot team"},{"id":"d","text":"Lack of executive enthusiasm"}]'::jsonb, 'c', 'Pilots succeed inside a protected environment. Scaling exposes the surrounding processes, data quality and unclear ownership that the pilot team quietly worked around.', true, 'approved'),
  ('BJ-08', 'business_judgment', 'medium', 'The board asks for your AI strategy. Which structure is most useful to them?', '[{"id":"a","text":"A detailed comparison of the leading AI vendors today"},{"id":"b","text":"A roadmap of technical milestones"},{"id":"c","text":"A catalogue of tools being evaluated"},{"id":"d","text":"A few business outcomes with owners and risks"}]'::jsonb, 'd', 'A board governs outcomes, accountability and risk. A tool catalogue tells them what you bought, not what it changes.', true, 'approved'),
  ('BJ-09', 'business_judgment', 'medium', 'Two teams report conflicting AI productivity gains using different measures. What should you do first?', '[{"id":"a","text":"Agree one definition and re-measure"},{"id":"b","text":"Escalate to the CFO and ask for a ruling"},{"id":"c","text":"Average the two figures"},{"id":"d","text":"Trust the more experienced team"}]'::jsonb, 'a', 'Conflicting numbers usually mean conflicting definitions, not dishonesty. Averaging or escalating settles a dispute without producing a usable number.', true, 'approved'),
  ('BJ-10', 'business_judgment', 'medium', 'A competitor announces a major AI capability. Your team wants to respond immediately. What is the disciplined move?', '[{"id":"a","text":"Match the announcement within the quarter"},{"id":"b","text":"Assess whether it changes your customer economics"},{"id":"c","text":"Announce a larger initiative"},{"id":"d","text":"Commission a market study before committing to anything"}]'::jsonb, 'b', 'A competitor announcement is information, not a mandate. The question is whether it shifts what your customers will pay for or expect.', true, 'approved'),
  ('BJ-11', 'business_judgment', 'hard', 'Your AI initiative shows strong local gains but no change in enterprise margin after a year. What is the most likely explanation?', '[{"id":"a","text":"Measurement periods were too short"},{"id":"b","text":"The gains were fabricated by teams"},{"id":"c","text":"Savings were absorbed, not captured"},{"id":"d","text":"The technology was the wrong choice"}]'::jsonb, 'c', 'Local efficiency typically dissipates into slack, rework or added scope unless someone deliberately captures it. That is an operating decision, not a technology failure.', true, 'approved'),
  ('BJ-12', 'business_judgment', 'hard', 'You must choose between an AI capability that is easy to build and one that is hard to copy. Which reasoning is soundest?', '[{"id":"a","text":"Neither — buy both capabilities from external vendors"},{"id":"b","text":"Easy to build wins, speed compounds"},{"id":"c","text":"Hard to copy wins, it protects margin"},{"id":"d","text":"Build easy now, hard next, funded by the first"}]'::jsonb, 'd', 'The two are not exclusive. Easy capability funds credibility and cash; durable advantage needs the hard one. Sequencing beats choosing.', true, 'approved'),
  ('BJ-13', 'business_judgment', 'easy', 'A team asks to build a custom AI tool that a vendor already sells. What should you weigh first?', '[{"id":"a","text":"Whether the capability is core to how you compete"},{"id":"b","text":"Whether the team would find building it more interesting"},{"id":"c","text":"Whether building looks cheaper in year one"},{"id":"d","text":"Whether the vendor is a well-known brand"}]'::jsonb, 'a', 'Build what differentiates you; buy what does not. Team interest, first-year cost and brand are weak grounds for owning long-term engineering.', true, 'approved'),
  ('BJ-14', 'business_judgment', 'easy', 'Before approving an AI pilot, which single question is most useful?', '[{"id":"a","text":"Which model will it use?"},{"id":"b","text":"What decision will change as a result?"},{"id":"c","text":"How long will it take to build?"},{"id":"d","text":"Who else in our industry has already tried it?"}]'::jsonb, 'b', 'A pilot that changes no decision produces a demo. Naming the decision it will move makes both value and failure measurable.', true, 'approved'),
  ('BJ-15', 'business_judgment', 'easy', 'A function requests AI budget but has no baseline for how the process performs today. What is the right response?', '[{"id":"a","text":"Approve it; baselines can be built later"},{"id":"b","text":"Reject the request outright"},{"id":"c","text":"Measure the current process first"},{"id":"d","text":"Halve the budget and proceed"}]'::jsonb, 'c', 'Without a baseline there is no way to prove improvement or to stop a failing pilot. Measuring first is cheap and makes the later claim credible.', true, 'approved'),
  ('BJ-16', 'business_judgment', 'easy', 'Where does AI usually create the least value in the short term?', '[{"id":"a","text":"Work that is high volume, repetitive and well documented"},{"id":"b","text":"Work with clear, checkable outputs"},{"id":"c","text":"Work that already runs on clean data"},{"id":"d","text":"Work that is rare, bespoke and judgment-heavy"}]'::jsonb, 'd', 'Value comes from repetition and checkability. Rare bespoke judgment offers few repetitions to learn from and a high cost when the answer is wrong.', true, 'approved'),
  ('BJ-17', 'business_judgment', 'medium', 'A vendor quotes a licence fee far below your internal build estimate. What is most often missing from that comparison?', '[{"id":"a","text":"Integration, data preparation and change effort"},{"id":"b","text":"The vendor''s own profit margin on the licence fee"},{"id":"c","text":"The cost of running the initial pilot"},{"id":"d","text":"Future licence price increases"}]'::jsonb, 'a', 'Licence cost is usually a minority of total cost. Integration, data work and getting people to change how they work dominate the real bill.', true, 'approved'),
  ('BJ-18', 'business_judgment', 'medium', 'You discover staff are widely using unapproved AI tools for real work. What does this most usefully tell you?', '[{"id":"a","text":"That policy enforcement has failed"},{"id":"b","text":"That the workforce is careless about confidential information"},{"id":"c","text":"That there is real demand and no sanctioned path"},{"id":"d","text":"That approved tools are technically inferior"}]'::jsonb, 'c', 'Widespread unofficial use is demand evidence. Treating it only as a discipline problem discards the signal about where sanctioned capability is missing.', true, 'approved'),
  ('BJ-19', 'business_judgment', 'medium', 'The CFO asks for the return on your AI programme after nine months. What is the most credible answer?', '[{"id":"a","text":"A projection of savings over five years"},{"id":"b","text":"Hours saved across all participating teams"},{"id":"c","text":"A benchmark of what comparable peer companies publicly report"},{"id":"d","text":"Measured outcomes on the few use cases with baselines"}]'::jsonb, 'd', 'Credibility comes from a small number of measured cases, not a large projection. Unbaselined hours are the claim finance trusts least.', true, 'approved'),
  ('BJ-20', 'business_judgment', 'medium', 'A critical AI capability depends entirely on one vendor. What is the most practical mitigation?', '[{"id":"a","text":"Negotiate a longer contract for price certainty"},{"id":"b","text":"Keep your data, prompts and evaluations portable"},{"id":"c","text":"Run two vendors in parallel across every production use case"},{"id":"d","text":"Start building an internal replacement now"}]'::jsonb, 'b', 'Portability preserves the ability to move without paying for permanent duplication. Longer contracts deepen the dependency they appear to manage.', true, 'approved'),
  ('BJ-21', 'business_judgment', 'medium', 'One team''s AI pilot delivered strong results. The sponsor wants an immediate enterprise rollout. What is the disciplined next step?', '[{"id":"a","text":"Roll out immediately and address problems as they surface"},{"id":"b","text":"Test it with a team working under different conditions"},{"id":"c","text":"Wait for a second successful pilot on the same team"},{"id":"d","text":"Commission an external validation of the results"}]'::jsonb, 'b', 'A single site cannot separate the tool from that team''s context. A deliberately different second site is the cheapest way to learn which one produced the result.', true, 'approved'),
  ('BJ-22', 'business_judgment', 'medium', 'An AI tool would cut customer response time but occasionally produces confidently wrong answers. What should determine whether you deploy?', '[{"id":"a","text":"Whether the measured error rate compares well with the industry norm"},{"id":"b","text":"Whether customers can tell the reply is AI-assisted"},{"id":"c","text":"Whether a wrong answer can be caught before it reaches the customer"},{"id":"d","text":"Whether the speed gain outweighs the error rate"}]'::jsonb, 'c', 'Deployability depends on containment, not the raw error rate. A recoverable error is an inconvenience; an unrecoverable one is a liability.', true, 'approved'),
  ('BJ-23', 'business_judgment', 'hard', 'You are allocating AI investment for the year. Which allocation logic is soundest?', '[{"id":"a","text":"Fund only initiatives with proven near-term payback"},{"id":"b","text":"Fund proven work, with a bounded share on option value"},{"id":"c","text":"Distribute the budget evenly across all functions"},{"id":"d","text":"Concentrate everything on the single largest opportunity"}]'::jsonb, 'b', 'Funding only proven work forfeits future position; funding only bets forfeits credibility. A bounded exploration share buys optionality without risking the base.', true, 'approved'),
  ('BJ-24', 'business_judgment', 'hard', 'An AI capability gives you an edge today, but competitors can buy the same tool tomorrow. Where is durable advantage most likely to sit?', '[{"id":"a","text":"In signing a longer exclusive vendor agreement"},{"id":"b","text":"In adopting the tool significantly earlier than your competitors"},{"id":"c","text":"In the proprietary data and workflow built around it"},{"id":"d","text":"In the size of the deployment budget"}]'::jsonb, 'c', 'Purchasable inputs equalise. What persists is the data, process and organisational skill a competitor cannot acquire with the same licence.', true, 'approved'),
  ('RA-01', 'responsible_ai', 'easy', 'Your recruitment team wants AI to automatically reject candidates using historical hiring data. What should happen first?', '[{"id":"a","text":"Test for bias and require accountable human review"},{"id":"b","text":"Restrict it to high-volume roles only"},{"id":"c","text":"Get written consent from applicants"},{"id":"d","text":"Launch with a short monitoring period and review later"}]'::jsonb, 'a', 'Historical hiring data encodes past preferences. Testing for disparate outcomes and keeping an accountable human in the loop addresses the cause, not just the optics.', true, 'approved'),
  ('RA-02', 'responsible_ai', 'easy', 'An employee pastes confidential client data into a public AI chat tool. What is the priority response?', '[{"id":"a","text":"Block all AI tools across the company immediately"},{"id":"b","text":"Contain the exposure, then fix the guidance"},{"id":"c","text":"Ask the vendor to delete the data"},{"id":"d","text":"Discipline the employee immediately"}]'::jsonb, 'b', 'Containment comes first, then the systemic gap. A single sanction or a blanket ban leaves the next employee in exactly the same position.', true, 'approved'),
  ('RA-03', 'responsible_ai', 'easy', 'Who should be accountable when an AI system used in HR produces a harmful outcome?', '[{"id":"a","text":"The vendor who supplied the model"},{"id":"b","text":"The data science team who built it"},{"id":"c","text":"The business leader who deployed it"},{"id":"d","text":"No single owner, it is shared"}]'::jsonb, 'c', 'Accountability follows the deployment decision. Shared or vendor-only ownership reliably produces no owner when something goes wrong.', true, 'approved'),
  ('RA-04', 'responsible_ai', 'easy', 'What is the clearest sign that an AI governance policy is working?', '[{"id":"a","text":"The policy document is comprehensive"},{"id":"b","text":"Every tool has been formally approved"},{"id":"c","text":"No incidents have been reported"},{"id":"d","text":"Teams raise concerns before launching"}]'::jsonb, 'd', 'Zero reports usually means zero reporting. A governance process is working when concerns surface early and cheaply.', true, 'approved'),
  ('RA-05', 'responsible_ai', 'medium', 'An AI screening tool selects fewer candidates from one region. The vendor says the model never sees location. What follows?', '[{"id":"a","text":"Investigate proxies correlated with location"},{"id":"b","text":"Add a quota to balance the outcome"},{"id":"c","text":"Switch to a different screening vendor immediately"},{"id":"d","text":"Accept it, location is not an input"}]'::jsonb, 'a', 'Removing a sensitive field does not remove its signal. Postcodes, institutions and employers routinely act as proxies, so the outcome must be examined, not the input list.', true, 'approved'),
  ('RA-06', 'responsible_ai', 'medium', 'Your AI vendor cannot explain how their model reaches a decision. What is the reasonable executive position?', '[{"id":"a","text":"Accept it if accuracy is high enough"},{"id":"b","text":"Match explainability to the decision stakes"},{"id":"c","text":"Require the source code in escrow"},{"id":"d","text":"Reject any model the vendor cannot fully explain"}]'::jsonb, 'b', 'Explainability requirements should scale with consequence. Demanding it everywhere blocks useful low-stakes work; demanding it nowhere is indefensible in hiring or pay.', true, 'approved'),
  ('RA-07', 'responsible_ai', 'medium', 'Employees ask whether AI is being used to monitor their productivity. What is the strongest response?', '[{"id":"a","text":"Refer the question to legal counsel"},{"id":"b","text":"Explain that the data is anonymised"},{"id":"c","text":"Confirm what is measured and why"},{"id":"d","text":"Reassure them that nothing has changed"}]'::jsonb, 'c', 'Ambiguity about monitoring destroys trust faster than monitoring itself. Naming what is measured and why is the only response that survives being tested.', true, 'approved'),
  ('RA-08', 'responsible_ai', 'medium', 'An AI assistant drafts performance feedback. Where should the strongest control sit?', '[{"id":"a","text":"On the content filters the vendor provides by default"},{"id":"b","text":"On an annual audit of outputs"},{"id":"c","text":"On the prompt template used"},{"id":"d","text":"On the manager who owns and signs the feedback"}]'::jsonb, 'd', 'The control must sit where the consequence lands. A template or filter shapes text; only the accountable manager can judge whether it is fair and true.', true, 'approved'),
  ('RA-09', 'responsible_ai', 'medium', 'How often should a deployed AI system used in people decisions be reviewed?', '[{"id":"a","text":"On a regular cycle and after material change"},{"id":"b","text":"Annually, aligned with the internal audit calendar"},{"id":"c","text":"Whenever the vendor releases an update"},{"id":"d","text":"Once at deployment, then on complaint"}]'::jsonb, 'a', 'Model behaviour drifts as data and populations shift. A fixed cadence plus triggers on material change catches drift that a complaint-driven process never sees.', true, 'approved'),
  ('RA-10', 'responsible_ai', 'medium', 'A business unit wants to skip AI review because their use case is "internal only". What is the right test?', '[{"id":"a","text":"All use cases need identical review"},{"id":"b","text":"Review depth follows impact on people"},{"id":"c","text":"Only customer-facing uses need review"},{"id":"d","text":"Internal use cases can proceed faster"}]'::jsonb, 'b', 'Internal systems make pay, promotion and staffing decisions. The right filter is the consequence for a person, not whether a customer sees it.', true, 'approved'),
  ('RA-11', 'responsible_ai', 'hard', 'Your AI hiring tool improves overall accuracy but slightly widens the gap between two candidate groups. What is the defensible decision?', '[{"id":"a","text":"Deploy only for senior roles"},{"id":"b","text":"Deploy, since overall accuracy improved"},{"id":"c","text":"Do not deploy on that measure alone"},{"id":"d","text":"Deploy and monitor the gap quarterly"}]'::jsonb, 'c', 'Aggregate accuracy can improve while a group is systematically disadvantaged. A widening gap is a result to be addressed before deployment, not monitored afterwards.', true, 'approved'),
  ('RA-12', 'responsible_ai', 'hard', 'Two AI principles conflict: full transparency about a model would expose personal data. How should this be resolved?', '[{"id":"a","text":"Escalate each case to the board for a decision"},{"id":"b","text":"Transparency always outweighs privacy"},{"id":"c","text":"Privacy always outweighs transparency"},{"id":"d","text":"Publish method and outcomes, not records"}]'::jsonb, 'd', 'The conflict is usually false. Explaining how a system works and reporting outcome statistics delivers accountability without exposing anyone''s data.', true, 'approved'),
  ('RA-13', 'responsible_ai', 'easy', 'What is the minimum an employee should be told when AI materially affects a decision about them?', '[{"id":"a","text":"That AI was involved and how to question the outcome"},{"id":"b","text":"The name of the model vendor"},{"id":"c","text":"The independently measured accuracy of the underlying system"},{"id":"d","text":"Nothing, provided a human signed it off"}]'::jsonb, 'a', 'Notice plus a route to challenge is the practical floor. Vendor names and accuracy figures do not help a person contest a decision that affects them.', true, 'approved'),
  ('RA-14', 'responsible_ai', 'easy', 'A team wants to reuse customer data to improve an AI system. What should be checked first?', '[{"id":"a","text":"Whether the data is technically accessible to the team"},{"id":"b","text":"Whether the original purpose covers this new use"},{"id":"c","text":"Whether competitors do the same thing"},{"id":"d","text":"Whether the data volume is sufficient"}]'::jsonb, 'b', 'Data collected for one purpose is not automatically available for another. Purpose fit is the first gate; technical feasibility is the second.', true, 'approved'),
  ('RA-15', 'responsible_ai', 'easy', 'Which record matters most if an AI-supported people decision is challenged a year later?', '[{"id":"a","text":"The vendor''s accuracy documentation"},{"id":"b","text":"The training completion log for the managers involved"},{"id":"c","text":"The policy in force at the time"},{"id":"d","text":"What the system recommended and who decided"}]'::jsonb, 'd', 'Challenges turn on the specific decision. A record of the recommendation and the accountable human is what makes it reviewable at all.', true, 'approved'),
  ('RA-16', 'responsible_ai', 'easy', 'An AI policy tells staff to "use AI responsibly". What is its main weakness?', '[{"id":"a","text":"It does not name a policy owner"},{"id":"b","text":"It is too short to be taken seriously"},{"id":"c","text":"It gives no testable guidance for real cases"},{"id":"d","text":"It fails to list the specific tools that are approved"}]'::jsonb, 'c', 'A principle nobody can apply to a Tuesday-afternoon decision changes nothing. Usable policy names allowed uses, prohibited uses and where to ask.', true, 'approved'),
  ('RA-17', 'responsible_ai', 'medium', 'A model is equally accurate across groups on average, but the type of error differs by group. What is the responsible reading?', '[{"id":"a","text":"Equal average accuracy means the model is fair"},{"id":"b","text":"Who bears which error matters, not just how many"},{"id":"c","text":"The difference is acceptable while it stays small"},{"id":"d","text":"Error types are a technical rather than governance matter"}]'::jsonb, 'b', 'A false rejection and a false acceptance land very differently on a person. Fairness has to consider the distribution of harm, not the headline rate.', true, 'approved'),
  ('RA-18', 'responsible_ai', 'medium', 'Your AI vendor updates their model without notice and your outputs change. Which governance gap does this expose?', '[{"id":"a","text":"Insufficient testing before the original launch"},{"id":"b","text":"Over-reliance on a single vendor"},{"id":"c","text":"Inadequate staff training on the tool"},{"id":"d","text":"No change notification or re-validation clause"}]'::jsonb, 'd', 'A system whose behaviour can change silently cannot be governed. Contractual notice and a re-validation trigger are what make ongoing assurance possible.', true, 'approved'),
  ('RA-19', 'responsible_ai', 'medium', 'Staff must review AI outputs, but are measured only on volume processed. What is the predictable result?', '[{"id":"a","text":"Reviewers escalate more cases to their managers"},{"id":"b","text":"Review quality improves through repeated practice"},{"id":"c","text":"Review becomes a rubber stamp"},{"id":"d","text":"Reviewers refuse to use the system"}]'::jsonb, 'c', 'People optimise for what is measured. A review step with no time allowance and no quality measure reliably decays into a formality.', true, 'approved'),
  ('RA-20', 'responsible_ai', 'medium', 'You must spread limited assurance effort across many AI systems. What is the strongest basis for prioritising?', '[{"id":"a","text":"The severity of impact on individuals"},{"id":"b","text":"The technical complexity of each system"},{"id":"c","text":"The annual cost of each system"},{"id":"d","text":"The number of users of each system"}]'::jsonb, 'a', 'Assurance is a risk instrument. Consequence for a person, not complexity or spend, determines how much scrutiny a system earns.', true, 'approved'),
  ('RA-21', 'responsible_ai', 'medium', 'A manager asks an AI tool to summarise an employee grievance to save time. What is the primary concern?', '[{"id":"a","text":"The summary may take as long to check as to write"},{"id":"b","text":"Sensitive detail and tone may be lost or distorted"},{"id":"c","text":"The tool may not support the required document format"},{"id":"d","text":"Other managers will expect the same access"}]'::jsonb, 'b', 'Grievances turn on specifics and tone. Compression is precisely the wrong operation on a document where the detail is the substance.', true, 'approved'),
  ('RA-22', 'responsible_ai', 'medium', 'You want one AI principle that staff will actually apply. Which is most operational?', '[{"id":"a","text":"\"We will always keep a human in the loop\""},{"id":"b","text":"\"We will use AI to benefit all of our stakeholders fairly\""},{"id":"c","text":"\"We will not deploy AI we cannot fully explain\""},{"id":"d","text":"\"If it materially affects someone, a named person decides\""}]'::jsonb, 'd', 'Operational principles tell you what to do on a specific case. Blanket in-the-loop and explainability rules either block useful work or get quietly ignored.', true, 'approved'),
  ('RA-23', 'responsible_ai', 'hard', 'An AI system reduces total harm but concentrates its remaining errors on one small group. How should this be handled?', '[{"id":"a","text":"Deploy it, since overall harm has fallen"},{"id":"b","text":"Reject any system whose errors are unequally distributed"},{"id":"c","text":"Deploy with targeted safeguards for the affected group"},{"id":"d","text":"Defer the decision to the vendor''s ethics board"}]'::jsonb, 'c', 'Aggregate improvement does not justify a concentrated burden, but nor does it require abandoning a better system. The obligation is to address the concentration directly.', true, 'approved'),
  ('RA-24', 'responsible_ai', 'hard', 'Regulators, customers and your own staff each want different AI transparency. How should you respond?', '[{"id":"a","text":"Publish one disclosure written to satisfy the strictest"},{"id":"b","text":"Disclose only what regulation currently requires"},{"id":"c","text":"Give each audience what it needs in order to act"},{"id":"d","text":"Delay disclosure until standards converge"}]'::jsonb, 'c', 'Transparency is purpose-built, not one document. A regulator needs assurance evidence, a customer needs plain notice, an employee needs a route to challenge.', true, 'approved'),
  ('HR-01', 'hr_workforce', 'easy', 'Which HR process is usually the safest place to introduce AI first?', '[{"id":"a","text":"Answering routine policy questions"},{"id":"b","text":"Performance ratings calibration"},{"id":"c","text":"Recommending which employees should be exited"},{"id":"d","text":"Final promotion decisions"}]'::jsonb, 'a', 'High volume, low stakes and an easily checked answer. Errors are visible and cheap, which is exactly what a first deployment needs.', true, 'approved'),
  ('HR-02', 'hr_workforce', 'easy', 'AI shortlisting cut time-to-shortlist by 60%, but hiring managers reject most shortlists. What does this indicate?', '[{"id":"a","text":"Hiring managers are resisting the new process"},{"id":"b","text":"The tool is optimising the wrong signal"},{"id":"c","text":"The tool needs more training data"},{"id":"d","text":"Shortlists should be made longer"}]'::jsonb, 'b', 'Speed to a shortlist nobody accepts is not a gain. The mismatch says the model is scoring something the hiring managers do not value.', true, 'approved'),
  ('HR-03', 'hr_workforce', 'easy', 'Your team wants AI to write job descriptions. What is the main risk to manage?', '[{"id":"a","text":"Recruiters will gradually lose the writing skill"},{"id":"b","text":"Descriptions will sound generic"},{"id":"c","text":"Inherited language narrows the applicant pool"},{"id":"d","text":"Legal will need to review each one"}]'::jsonb, 'c', 'Generated text reproduces patterns in the source material, including phrasing that has historically discouraged parts of the market from applying.', true, 'approved'),
  ('HR-04', 'hr_workforce', 'easy', 'An AI tool predicts which employees are likely to resign. What is the most responsible use?', '[{"id":"a","text":"Prioritise replacement hiring in advance"},{"id":"b","text":"Flag individuals to their managers"},{"id":"c","text":"Reduce increments for likely leavers"},{"id":"d","text":"Find the systemic drivers and fix them"}]'::jsonb, 'd', 'Individual flags invite pre-emptive and often unfair treatment. The value of the signal is in the pattern it reveals about the work, not the name it produces.', true, 'approved'),
  ('HR-05', 'hr_workforce', 'medium', 'Recruiters say AI-generated candidate summaries are accurate but they still read every CV. What is the likely cause?', '[{"id":"a","text":"Recruiters do not trust unverifiable output"},{"id":"b","text":"The tool is poorly integrated"},{"id":"c","text":"Recruiters were not trained on the new tool properly"},{"id":"d","text":"The summaries are too short"}]'::jsonb, 'a', 'People will not act on a summary they cannot check. Showing the source alongside the summary usually changes behaviour more than more training does.', true, 'approved'),
  ('HR-06', 'hr_workforce', 'medium', 'You are asked to use AI to make performance reviews more consistent. What is the strongest approach?', '[{"id":"a","text":"Let AI generate the rating from data"},{"id":"b","text":"Use AI to surface evidence managers may have missed"},{"id":"c","text":"Use AI to rewrite reviews in a uniform tone"},{"id":"d","text":"Use AI to rank each employee against their peer group"}]'::jsonb, 'b', 'The problem in reviews is usually missing or recency-weighted evidence. Improving the input preserves managerial accountability; generating the rating removes it.', true, 'approved'),
  ('HR-07', 'hr_workforce', 'medium', 'An AI chatbot handles 70% of HR queries. Employee satisfaction with HR has fallen. What should you examine first?', '[{"id":"a","text":"Whether employees prefer email"},{"id":"b","text":"The chatbot''s accuracy rate"},{"id":"c","text":"What happens to the other 30%"},{"id":"d","text":"The chatbot''s tone of voice"}]'::jsonb, 'c', 'Deflection metrics hide the hard cases. The queries that fall through are usually the sensitive ones, and that is where the experience is now worse.', true, 'approved'),
  ('HR-08', 'hr_workforce', 'medium', 'Your organisation wants an AI skills inventory. What most determines whether it will be useful?', '[{"id":"a","text":"The number of systems integrated"},{"id":"b","text":"The size of the skills taxonomy"},{"id":"c","text":"Whether employees keep profiles updated"},{"id":"d","text":"Whether inferred skills are validated"}]'::jsonb, 'd', 'Inferred skills are cheap to produce and easy to over-trust. Without validation the inventory becomes a confident record of things people cannot actually do.', true, 'approved'),
  ('HR-09', 'hr_workforce', 'medium', 'AI interview scoring is proposed to reduce interviewer bias. What is the most important safeguard?', '[{"id":"a","text":"Interviewers should not see AI scores first"},{"id":"b","text":"Scores should be weighted at 50%"},{"id":"c","text":"Candidates should consent in writing"},{"id":"d","text":"Only interviewers who have been trained should use it"}]'::jsonb, 'a', 'Showing a score before the human forms a view anchors the human to it. Sequencing preserves the independent judgment the tool was meant to complement.', true, 'approved'),
  ('HR-10', 'hr_workforce', 'medium', 'Learning teams want AI to personalise development paths. What is the most common failure mode?', '[{"id":"a","text":"Content libraries are too small"},{"id":"b","text":"Recommendations reinforce current roles"},{"id":"c","text":"Employees ignore recommendations"},{"id":"d","text":"Costs rise faster than anyone expected them to"}]'::jsonb, 'b', 'Recommenders trained on what similar people did tend to route people deeper into their existing track, quietly suppressing the career moves development is meant to enable.', true, 'approved'),
  ('HR-11', 'hr_workforce', 'hard', 'AI reduces recruiter screening time by half. Time-to-hire is unchanged. Where should you look?', '[{"id":"a","text":"Recruiter capacity planning"},{"id":"b","text":"The screening model''s precision"},{"id":"c","text":"The stage after screening"},{"id":"d","text":"The volume of applications"}]'::jsonb, 'c', 'Removing a constraint moves it. If total time is unchanged, the bottleneck was never screening — it is now visible at interview scheduling or decision-making.', true, 'approved'),
  ('HR-12', 'hr_workforce', 'hard', 'An AI tool recommends pay adjustments. Two managers with similar teams get very different recommendations. What is the right first step?', '[{"id":"a","text":"Override both with manager judgment"},{"id":"b","text":"Suspend the tool pending review"},{"id":"c","text":"Average the two recommendations"},{"id":"d","text":"Ask which inputs differed and why"}]'::jsonb, 'd', 'Divergent output is a finding, not a fault. It may reflect a real difference in the teams or a data problem, and you cannot tell which without inspecting the inputs.', true, 'approved'),
  ('HR-13', 'hr_workforce', 'easy', 'What is the safest first HR use of AI for a team new to it?', '[{"id":"a","text":"Scoring candidates for shortlisting"},{"id":"b","text":"Drafting internal policy summaries for review"},{"id":"c","text":"Recommending promotion decisions"},{"id":"d","text":"Predicting individual performance ratings in advance"}]'::jsonb, 'b', 'Low stakes, easily checked, and no decision about a person. The other three attach someone''s livelihood to an unproven system.', true, 'approved'),
  ('HR-14', 'hr_workforce', 'easy', 'An AI tool drafts an offer letter containing the wrong salary figure. Where does accountability sit?', '[{"id":"a","text":"With the vendor that supplied the tool"},{"id":"b","text":"With the AI system that produced the error"},{"id":"c","text":"With the person who approved and sent it"},{"id":"d","text":"Shared equally across everyone involved"}]'::jsonb, 'c', 'Accountability attaches to the human who released the document. Diffusing it across a vendor or a system reliably means nobody owns the correction.', true, 'approved'),
  ('HR-15', 'hr_workforce', 'easy', 'When deploying AI in recruitment, which stakeholder is most often overlooked?', '[{"id":"a","text":"The finance team approving the spend"},{"id":"b","text":"The IT security function"},{"id":"c","text":"The candidates being assessed"},{"id":"d","text":"The executive sponsor"}]'::jsonb, 'c', 'Candidates carry the consequence and have the least voice. Their experience of the process is also what shapes your reputation as an employer.', true, 'approved'),
  ('HR-16', 'hr_workforce', 'easy', 'A vendor claims their tool assesses candidate "culture fit" from video interviews. What is the right posture?', '[{"id":"a","text":"Adopt it if the accuracy claim is high enough"},{"id":"b","text":"Pilot it on existing employees first"},{"id":"c","text":"Adopt it for senior roles only"},{"id":"d","text":"Treat the underlying claim as unproven"}]'::jsonb, 'd', 'The issue is not the accuracy figure but what is being measured. Inferring fit from appearance and speech is a contested claim, not a settled capability.', true, 'approved'),
  ('HR-17', 'hr_workforce', 'medium', 'Managers report that AI-drafted performance feedback all sounds the same. What is the underlying problem?', '[{"id":"a","text":"The tool needs a wider range of templates"},{"id":"b","text":"Managers need better prompting technique and practice"},{"id":"c","text":"The drafts are not grounded in specific evidence"},{"id":"d","text":"Performance feedback is inherently repetitive"}]'::jsonb, 'c', 'Generic output signals generic input. Feedback becomes distinctive when it is built from that person''s actual work, not from better phrasing.', true, 'approved'),
  ('HR-18', 'hr_workforce', 'medium', 'AI screening doubles applicant throughput, but quality of hire is unchanged. What has actually improved?', '[{"id":"a","text":"The quality of the candidate pool"},{"id":"b","text":"Recruiter capacity, not hiring outcomes"},{"id":"c","text":"The demonstrable fairness of the selection process"},{"id":"d","text":"The employer brand in the market"}]'::jsonb, 'b', 'Processing more applications faster is a capacity gain. Until quality of hire moves, nothing about the outcome of hiring has changed.', true, 'approved'),
  ('HR-19', 'hr_workforce', 'medium', 'You want AI to surface internal candidates for open roles. What most determines whether it is fair?', '[{"id":"a","text":"Whether the model is retrained frequently"},{"id":"b","text":"Whether hiring managers can override the suggested shortlist"},{"id":"c","text":"Whether the tool explains its reasoning"},{"id":"d","text":"Whether the records reflect opportunity, not just outcomes"}]'::jsonb, 'd', 'Internal records capture who was given chances, not only who performed. A model trained on them will faithfully reproduce past access to opportunity.', true, 'approved'),
  ('HR-20', 'hr_workforce', 'medium', 'A wellbeing tool flags individual employees showing declining engagement signals. What is the most defensible use?', '[{"id":"a","text":"Alert each person''s line manager directly"},{"id":"b","text":"Trigger an automatic outreach call from HR"},{"id":"c","text":"Add the individual flags to retention planning reviews"},{"id":"d","text":"Use aggregate patterns to fix team conditions"}]'::jsonb, 'd', 'Individual inference from behavioural signals is intrusive and often wrong. The same data is both legitimate and more useful read at team level.', true, 'approved'),
  ('HR-21', 'hr_workforce', 'medium', 'HR plans to publish an AI-generated summary of engagement survey comments. What is the main risk?', '[{"id":"a","text":"Comments from small teams may become identifiable"},{"id":"b","text":"The summary may be too long for people to read"},{"id":"c","text":"Employees may not trust an automated summary of their words"},{"id":"d","text":"The tool may handle multiple languages poorly"}]'::jsonb, 'a', 'Aggregation protects privacy only when the groups are large. Summarising a team of six can re-identify the person who raised a concern.', true, 'approved'),
  ('HR-22', 'hr_workforce', 'medium', 'You are asked to cut HR headcount because AI has automated part of the function. What should you establish first?', '[{"id":"a","text":"Which equivalent roles competitors have already reduced"},{"id":"b","text":"Whether the automated work was the real bottleneck"},{"id":"c","text":"How quickly the savings can be booked"},{"id":"d","text":"Which individuals are least engaged"}]'::jsonb, 'b', 'Automating a step that was not the constraint frees capacity without increasing output. Cutting on that basis removes capability you still need.', true, 'approved'),
  ('HR-23', 'hr_workforce', 'hard', 'AI has absorbed most transactional HR work. What is the hardest part of redesigning the function?', '[{"id":"a","text":"Selecting the right technology platform"},{"id":"b","text":"Rebuilding the judgment that transactional work used to teach"},{"id":"c","text":"Renegotiating vendor contracts"},{"id":"d","text":"Communicating the change to employees and their representatives"}]'::jsonb, 'b', 'Transactional work was also the apprenticeship. Removing it without a deliberate replacement leaves a function that cannot grow its next generation of advisers.', true, 'approved'),
  ('HR-24', 'hr_workforce', 'hard', 'Two years after deploying AI across HR, efficiency metrics have improved but employee trust in HR has fallen. What is the most likely cause?', '[{"id":"a","text":"Employees dislike technology in principle"},{"id":"b","text":"The efficiency metrics are being measured incorrectly"},{"id":"c","text":"The tools were not explained well enough at launch"},{"id":"d","text":"Speed replaced contact in the moments that mattered"}]'::jsonb, 'd', 'Trust in HR is built in the difficult, personal cases. Optimising the whole function for throughput removes exactly the contact those cases require.', true, 'approved'),
  ('WD-01', 'work_design', 'easy', 'When redesigning a process around AI, what should be decided first?', '[{"id":"a","text":"Which decisions stay with people"},{"id":"b","text":"How many roles can be reduced"},{"id":"c","text":"What the training plan looks like"},{"id":"d","text":"Which tool to buy"}]'::jsonb, 'a', 'The boundary between human and machine judgment defines the whole design. Tooling, structure and training all follow from it.', true, 'approved'),
  ('WD-02', 'work_design', 'easy', 'A team uses AI to draft all client emails. What is the main design risk?', '[{"id":"a","text":"Emails become too long"},{"id":"b","text":"Review becomes rubber-stamping"},{"id":"c","text":"Clients notice the change"},{"id":"d","text":"Drafting skills atrophy slowly"}]'::jsonb, 'b', 'When output is usually good, reviewers stop reading. A control that is never exercised is not a control, and the rare bad draft goes straight out.', true, 'approved'),
  ('WD-03', 'work_design', 'easy', 'Which task split between a person and an AI system is usually strongest?', '[{"id":"a","text":"AI and human work in parallel"},{"id":"b","text":"AI decides, human audits samples"},{"id":"c","text":"AI drafts, human judges and owns"},{"id":"d","text":"Human drafts, AI approves"}]'::jsonb, 'c', 'Generation is cheap and reversible; judgment carries the consequence. Keeping ownership with the person matches control to accountability.', true, 'approved'),
  ('WD-04', 'work_design', 'easy', 'Your AI assistant is right 95% of the time. How should the workflow treat the other 5%?', '[{"id":"a","text":"Add a disclaimer to outputs"},{"id":"b","text":"Retrain until the rate improves"},{"id":"c","text":"Accept it as an acceptable error rate"},{"id":"d","text":"Design a way to detect and catch them"}]'::jsonb, 'd', 'The question is never the rate, it is whether the wrong 5% is detectable before it causes harm. Design for detection, not for a better average.', true, 'approved'),
  ('WD-05', 'work_design', 'medium', 'After AI automates routine work, junior staff have less to practise on. What is the strongest response?', '[{"id":"a","text":"Redesign early roles around judgment and review"},{"id":"b","text":"Hire more experienced staff instead"},{"id":"c","text":"Lengthen the graduate programme by another full year"},{"id":"d","text":"Keep some routine work manual"}]'::jsonb, 'a', 'Preserving obsolete work to train people is expensive and demotivating. The durable answer is to move junior development up to the judgment layer earlier.', true, 'approved'),
  ('WD-06', 'work_design', 'medium', 'Which signal best indicates that a human review step has become meaningless?', '[{"id":"a","text":"Review is done in batches"},{"id":"b","text":"Reviewers rarely change the output"},{"id":"c","text":"Review takes longer than expected"},{"id":"d","text":"Reviewers ask for more context"}]'::jsonb, 'b', 'A review step that almost never changes anything is either unnecessary or unexercised. Either way it is providing assurance it does not actually deliver.', true, 'approved'),
  ('WD-07', 'work_design', 'medium', 'You are designing an AI-assisted role. How should the job description change?', '[{"id":"a","text":"Add a technology aptitude assessment at the hiring stage"},{"id":"b","text":"Add AI tool proficiency requirements"},{"id":"c","text":"Describe accountability for AI-assisted outcomes"},{"id":"d","text":"Remove tasks the AI now performs"}]'::jsonb, 'c', 'Tool lists date within months. What endures is being explicit that the person owns the outcome regardless of how much of it was machine-produced.', true, 'approved'),
  ('WD-08', 'work_design', 'medium', 'An AI system surfaces recommendations that experienced staff frequently override. What is the best interpretation?', '[{"id":"a","text":"The system should be switched off"},{"id":"b","text":"Override rights should be restricted to senior staff"},{"id":"c","text":"Staff are resisting the system"},{"id":"d","text":"Overrides carry information worth capturing"}]'::jsonb, 'd', 'A consistent override pattern is free, expert-labelled feedback about what the model is missing. Suppressing it discards the most valuable signal available.', true, 'approved'),
  ('WD-09', 'work_design', 'medium', 'Where should an AI-assisted workflow place its human checkpoint?', '[{"id":"a","text":"At the end, before the outcome is final"},{"id":"b","text":"At the start, before the AI runs"},{"id":"c","text":"At every step, to give complete oversight"},{"id":"d","text":"At a random sample of steps"}]'::jsonb, 'a', 'The checkpoint belongs where reversal is still possible and consequence is about to land. Checking everywhere is theatre; checking too early misses what the system produced.', true, 'approved'),
  ('WD-10', 'work_design', 'medium', 'Two teams do the same work; one uses AI heavily, one barely. Quality is identical. What is the useful question?', '[{"id":"a","text":"How do we get the second team to adopt?"},{"id":"b","text":"What does the AI-heavy team do with the time?"},{"id":"c","text":"Should we standardise on one approach?"},{"id":"d","text":"Is the quality measure sensitive enough to detect it?"}]'::jsonb, 'b', 'Identical quality means the value, if any, is in released capacity. Until you know where that time went, adoption for its own sake is not yet justified.', true, 'approved'),
  ('WD-11', 'work_design', 'hard', 'An AI system performs well individually but team output has not improved. What is the most likely cause?', '[{"id":"a","text":"The training provided was clearly insufficient"},{"id":"b","text":"Individuals use it inconsistently"},{"id":"c","text":"Handoffs and coordination are the constraint"},{"id":"d","text":"The measurement window is too short"}]'::jsonb, 'c', 'Speeding up individual steps does not speed up a system governed by its handoffs. The constraint sits between people, where an individual assistant cannot reach.', true, 'approved'),
  ('WD-12', 'work_design', 'hard', 'You must decide how much AI output an expert should see before making a judgment. What principle applies?', '[{"id":"a","text":"Show only high-confidence output"},{"id":"b","text":"Show everything, experts can filter"},{"id":"c","text":"Show nothing until the expert decides"},{"id":"d","text":"Show evidence first, conclusion after"}]'::jsonb, 'd', 'Leading with a conclusion anchors the expert to it. Presenting the evidence first preserves independent judgment while still delivering the machine''s value.', true, 'approved'),
  ('WD-13', 'work_design', 'easy', 'What is the clearest sign that an AI-assisted workflow has been designed well?', '[{"id":"a","text":"People can explain when to trust the output"},{"id":"b","text":"The AI handles the majority of the steps"},{"id":"c","text":"The workflow has fewer total steps than before"},{"id":"d","text":"Staff report that the tool is enjoyable to use"}]'::jsonb, 'a', 'Calibrated trust is the design goal. Fewer steps and a higher automation share are means, and enjoyment is not evidence of good judgment.', true, 'approved'),
  ('WD-14', 'work_design', 'easy', 'When adding AI to an existing process, what is the most common design mistake?', '[{"id":"a","text":"Choosing the wrong model for the task"},{"id":"b","text":"Automating the current process without redesigning it"},{"id":"c","text":"Involving too many different stakeholders too early in design"},{"id":"d","text":"Setting the pilot period too short"}]'::jsonb, 'b', 'Existing processes contain steps that exist only because humans were doing the work. Automating those faithfully preserves the waste at higher speed.', true, 'approved'),
  ('WD-15', 'work_design', 'easy', 'Which work is best suited to AI drafting with human finishing?', '[{"id":"a","text":"A first draft of routine meeting notes"},{"id":"b","text":"A board paper recommending a restructure"},{"id":"c","text":"A disciplinary outcome letter"},{"id":"d","text":"A negotiating position for a key supplier"}]'::jsonb, 'a', 'Drafting suits high-volume, low-consequence work with an easy check. The others carry consequences that require the human to own the reasoning from the start.', true, 'approved'),
  ('WD-16', 'work_design', 'easy', 'Staff say an AI tool is "faster, but I still check everything". What should you conclude?', '[{"id":"a","text":"They need more training on the tool"},{"id":"b","text":"The tool should be withdrawn"},{"id":"c","text":"Checking behaviour will decline naturally as familiarity grows"},{"id":"d","text":"They have no basis yet for knowing when to trust it"}]'::jsonb, 'd', 'Universal checking is a rational response to unknown reliability. Publishing where the tool is strong and weak is what lets people check selectively.', true, 'approved'),
  ('WD-17', 'work_design', 'medium', 'You are designing an AI-assisted approval workflow. Where does the human step add most value?', '[{"id":"a","text":"Confirming every single AI output before it is released"},{"id":"b","text":"Handling the cases the system flags as uncertain"},{"id":"c","text":"Reviewing a random sample after release"},{"id":"d","text":"Approving each output in strict sequence"}]'::jsonb, 'b', 'Routing exceptions to humans concentrates scarce attention where the system is weakest. Blanket confirmation spends the same attention on the easy majority.', true, 'approved'),
  ('WD-18', 'work_design', 'medium', 'An AI tool makes a task 40% faster, but staff must now verify its output, so net time saved is small. What does this suggest?', '[{"id":"a","text":"The verification step itself has been designed badly"},{"id":"b","text":"The tool should be applied to a different task"},{"id":"c","text":"Verification cost was left out of the business case"},{"id":"d","text":"The team is resisting the new way of working"}]'::jsonb, 'c', 'Verification is part of the work, not overhead outside it. A business case that counts only generation time systematically overstates the gain.', true, 'approved'),
  ('WD-19', 'work_design', 'medium', 'Which role change is most often missed when AI enters knowledge work?', '[{"id":"a","text":"The need for substantially more technical specialists"},{"id":"b","text":"The shift from producing work to evaluating it"},{"id":"c","text":"The reduction in required headcount"},{"id":"d","text":"The increase in meeting frequency"}]'::jsonb, 'b', 'The task moves from writing the answer to judging one. That is a different skill, and job design and development rarely catch up with it.', true, 'approved'),
  ('WD-20', 'work_design', 'medium', 'Should AI-generated content be labelled as such inside an internal workflow? What matters most?', '[{"id":"a","text":"Whether the next person needs it to judge the work"},{"id":"b","text":"Whether labelling slows the process down"},{"id":"c","text":"Whether staff say they would prefer to know"},{"id":"d","text":"Whether competitors in your sector label their own outputs"}]'::jsonb, 'a', 'Provenance matters when it changes how the receiver should scrutinise the work. Labelling for its own sake becomes noise people stop reading.', true, 'approved'),
  ('WD-21', 'work_design', 'medium', 'A team automates one step and errors downstream increase. What is the most likely explanation?', '[{"id":"a","text":"The automation is technically faulty"},{"id":"b","text":"Downstream staff need more training on the new process"},{"id":"c","text":"The step was doing unrecognised quality control"},{"id":"d","text":"Error reporting has simply improved"}]'::jsonb, 'c', 'Manual steps often carry informal checks nobody documented. Removing the step removes the check, and the failure surfaces further along the chain.', true, 'approved'),
  ('WD-22', 'work_design', 'medium', 'How should you decide the pace at which an AI system takes on more of a workflow?', '[{"id":"a","text":"By the accuracy improvements achieved during controlled testing"},{"id":"b","text":"By the reduction in cost per transaction"},{"id":"c","text":"By how comfortable the team feels with the tool"},{"id":"d","text":"By demonstrated reliability on live exception cases"}]'::jsonb, 'd', 'Expansion should be earned on the hard cases, not the average ones. Test accuracy and team comfort both overstate readiness for the work that actually fails.', true, 'approved'),
  ('WD-23', 'work_design', 'hard', 'An AI system and an expert disagree. The expert is right 70% of the time, the system 80%. What is the strongest workflow design?', '[{"id":"a","text":"Follow the system, since it is more accurate overall"},{"id":"b","text":"Follow the expert, who carries the accountability"},{"id":"c","text":"Alternate according to the system''s confidence score"},{"id":"d","text":"Examine where each one is reliably stronger"}]'::jsonb, 'd', 'Aggregate accuracy hides structure. The valuable design routes each case to whichever is stronger on that type, rather than picking one overall winner.', true, 'approved'),
  ('WD-24', 'work_design', 'hard', 'Over time an AI-assisted team''s output improves while its ability to work without the tool declines. How should this be managed?', '[{"id":"a","text":"Accept it, since the tool will remain available"},{"id":"b","text":"Restrict tool use to preserve the underlying skill"},{"id":"c","text":"Decide which capabilities must survive an outage"},{"id":"d","text":"Rotate staff between assisted and unassisted work"}]'::jsonb, 'c', 'Some deskilling is an acceptable trade and some is an operational risk. The decision worth making explicitly is which capabilities you cannot afford to lose.', true, 'approved'),
  ('AC-01', 'adoption_change', 'easy', 'You roll out an AI tool to 500 people. After a month, 12% use it weekly. What should you investigate first?', '[{"id":"a","text":"What the 12% do differently"},{"id":"b","text":"Whether the tool should be mandated"},{"id":"c","text":"Whether a different tool is better"},{"id":"d","text":"Whether more training is needed"}]'::jsonb, 'a', 'The active minority has already solved the adoption problem for their own work. Understanding their use case is faster and more reliable than guessing at barriers.', true, 'approved'),
  ('AC-02', 'adoption_change', 'easy', 'Which message is most likely to build genuine support for an AI rollout?', '[{"id":"a","text":"\"This will make us more competitive\""},{"id":"b","text":"\"Here is what changes in your week\""},{"id":"c","text":"\"Nobody will lose their job\""},{"id":"d","text":"\"Leadership is fully committed\""}]'::jsonb, 'b', 'Abstract benefit statements and reassurances do not survive contact with a changed workflow. Concrete detail about the actual week is what people can act on.', true, 'approved'),
  ('AC-03', 'adoption_change', 'easy', 'Senior leaders publicly champion AI but never use it themselves. What is the effect?', '[{"id":"a","text":"Negative only for technical teams"},{"id":"b","text":"Neutral, sponsorship is what matters"},{"id":"c","text":"The initiative is read as optional"},{"id":"d","text":"Positive, it avoids micromanagement"}]'::jsonb, 'c', 'Teams calibrate priority from behaviour, not announcements. Visible non-use by leaders is read as permission to wait.', true, 'approved'),
  ('AC-04', 'adoption_change', 'easy', 'An experienced manager resists an AI tool, saying it misses context. What is the best first response?', '[{"id":"a","text":"Pair them with an enthusiastic user"},{"id":"b","text":"Set a usage target for their team"},{"id":"c","text":"Explain the business case again"},{"id":"d","text":"Ask for specific examples"}]'::jsonb, 'd', 'Experienced resistance is usually specific and often correct. Examples either fix the tool or identify the real objection, which persuasion alone cannot.', true, 'approved'),
  ('AC-05', 'adoption_change', 'medium', 'You have budget to either buy more AI licences or fund enablement. Adoption is at 20%. What is the stronger choice?', '[{"id":"a","text":"Enablement, since access is not the constraint"},{"id":"b","text":"Split the budget evenly between the two, to hedge"},{"id":"c","text":"Neither, wait for adoption to rise"},{"id":"d","text":"More licences, to widen access"}]'::jsonb, 'a', 'At 20% usage the unused licences already prove access is not the binding constraint. Buying more of a non-constraint is the most common AI budget error.', true, 'approved'),
  ('AC-06', 'adoption_change', 'medium', 'Employees fear AI will replace their roles. Which action most reduces that fear?', '[{"id":"a","text":"A public no-redundancy guarantee"},{"id":"b","text":"Naming what the role becomes accountable for"},{"id":"c","text":"A town hall with the CEO"},{"id":"d","text":"Sharing the full AI strategy document with everyone"}]'::jsonb, 'b', 'Guarantees are rarely believed and often cannot be honoured. Concrete clarity about the future shape of the role is what actually reduces uncertainty.', true, 'approved'),
  ('AC-07', 'adoption_change', 'medium', 'Your AI rollout has strong usage but people report no time saved. What is the likely issue?', '[{"id":"a","text":"Time savings take longer than this to appear"},{"id":"b","text":"The tool is genuinely not useful"},{"id":"c","text":"AI work was added on top of existing work"},{"id":"d","text":"Usage metrics are being gamed"}]'::jsonb, 'c', 'Adoption without removing a step means the new work is additive. Unless something is retired from the process, high usage produces effort rather than savings.', true, 'approved'),
  ('AC-08', 'adoption_change', 'medium', 'Which group is usually the most effective early target for an enterprise AI rollout?', '[{"id":"a","text":"A cross-section representing all functions"},{"id":"b","text":"The most senior leaders"},{"id":"c","text":"The most technically capable team"},{"id":"d","text":"A team with a painful, frequent problem"}]'::jsonb, 'd', 'Adoption follows relief. A team with acute, repeated pain will push through rough edges and produce a credible internal story that a representative sample never generates.', true, 'approved'),
  ('AC-09', 'adoption_change', 'medium', 'You must choose a metric to track AI adoption maturity. Which is most meaningful?', '[{"id":"a","text":"Decisions or outputs changed by AI"},{"id":"b","text":"Training hours completed"},{"id":"c","text":"Weekly active users"},{"id":"d","text":"The number of AI tools deployed across teams"}]'::jsonb, 'a', 'Logins and licences measure activity. Adoption only matters where it changes what the organisation actually produces or decides.', true, 'approved'),
  ('AC-10', 'adoption_change', 'medium', 'A high-profile AI project fails publicly. What is the most useful leadership response?', '[{"id":"a","text":"Pause the other AI work pending a full review"},{"id":"b","text":"Publish what was learned and what continues"},{"id":"c","text":"Reassign the project leadership"},{"id":"d","text":"Reduce the visibility of future projects"}]'::jsonb, 'b', 'How the first failure is handled sets the risk appetite for everything after. Visible learning keeps experimentation alive; a pause or a scapegoat ends it.', true, 'approved'),
  ('AC-11', 'adoption_change', 'hard', 'AI adoption is high in one region and low in another with identical tools and training. What should you examine?', '[{"id":"a","text":"Variation in internet reliability"},{"id":"b","text":"Local language and interface fit"},{"id":"c","text":"Whether local managers changed the work"},{"id":"d","text":"Regional differences in technical skill"}]'::jsonb, 'c', 'When inputs are identical, the difference is in the operating environment. Adoption tracks whether local leaders actually redesigned the work to use the tool.', true, 'approved'),
  ('AC-12', 'adoption_change', 'hard', 'Two years into AI adoption, capability is uneven across the organisation. What is the strongest structural response?', '[{"id":"a","text":"Let each function proceed at its own pace"},{"id":"b","text":"Rerun the enterprise-wide training programme again"},{"id":"c","text":"Centralise all AI work in one team"},{"id":"d","text":"Mandate minimum standards, keep delivery local"}]'::jsonb, 'd', 'Full centralisation starves the context where value is created; full autonomy entrenches the gap. Common standards with local delivery addresses both at once.', true, 'approved'),
  ('AC-13', 'adoption_change', 'easy', 'What is the most reliable early signal that an AI rollout is working?', '[{"id":"a","text":"Licence activation numbers"},{"id":"b","text":"Positive sentiment in the launch survey"},{"id":"c","text":"Attendance at training sessions"},{"id":"d","text":"Repeat use for real work"}]'::jsonb, 'd', 'People return to tools that help them. Activations, sentiment and attendance all measure exposure rather than usefulness.', true, 'approved'),
  ('AC-14', 'adoption_change', 'easy', 'Who is usually best placed to explain why an AI tool is worth using?', '[{"id":"a","text":"The vendor''s dedicated customer success team"},{"id":"b","text":"A peer who already uses it for the same work"},{"id":"c","text":"The executive sponsor of the programme"},{"id":"d","text":"The internal communications team"}]'::jsonb, 'b', 'Credibility comes from someone doing the same job. Sponsors set direction, but peers answer the question people actually have: does it help with my work?', true, 'approved'),
  ('AC-15', 'adoption_change', 'easy', 'Your AI training is well attended but usage stays flat. What is the most likely gap?', '[{"id":"a","text":"The training did not connect to people''s actual tasks"},{"id":"b","text":"The sessions were too short"},{"id":"c","text":"The wrong people attended the sessions that were offered"},{"id":"d","text":"The tool needs more features"}]'::jsonb, 'a', 'Generic capability training rarely converts. Usage moves when someone shows a person how the tool changes a task they are doing this week.', true, 'approved'),
  ('AC-16', 'adoption_change', 'easy', 'An AI rollout meets strong resistance from a key team. What should you do first?', '[{"id":"a","text":"Escalate to their senior leader"},{"id":"b","text":"Make tool usage a formal performance objective"},{"id":"c","text":"Find out what the resistance is protecting"},{"id":"d","text":"Move on to a more willing team"}]'::jsonb, 'c', 'Resistance usually encodes real knowledge about the work. Understanding it costs one conversation and frequently improves the rollout itself.', true, 'approved'),
  ('AC-17', 'adoption_change', 'medium', 'You can pilot AI with enthusiastic volunteers or with a representative team. Which teaches you more about scaling?', '[{"id":"a","text":"Volunteers, because they will push the tool hardest"},{"id":"b","text":"A representative team, sceptics included"},{"id":"c","text":"Whichever team has the cleanest data"},{"id":"d","text":"The team with the strongest leadership support"}]'::jsonb, 'b', 'Volunteers succeed under conditions you cannot replicate at scale. A representative team surfaces the friction the wider rollout will actually meet.', true, 'approved'),
  ('AC-18', 'adoption_change', 'medium', 'Six months in, AI usage is concentrated in one department. What is the most useful diagnostic question?', '[{"id":"a","text":"What is different about how that department works?"},{"id":"b","text":"How do we copy their training approach?"},{"id":"c","text":"Why are the other departments less capable?"},{"id":"d","text":"Should we now mandate usage across every other department?"}]'::jsonb, 'a', 'Concentrated adoption is a natural experiment. Understanding what makes that context work is what tells you whether it transfers at all.', true, 'approved'),
  ('AC-19', 'adoption_change', 'medium', 'Which change most reliably increases sustained AI use in a team?', '[{"id":"a","text":"Providing access to more capable models"},{"id":"b","text":"Publishing a usage leaderboard"},{"id":"c","text":"Running refresher training sessions every single quarter"},{"id":"d","text":"Removing a step the tool has made unnecessary"}]'::jsonb, 'd', 'Adoption sticks when the work itself changes. Leaderboards and refreshers apply pressure without altering the process people are actually following.', true, 'approved'),
  ('AC-20', 'adoption_change', 'medium', 'An AI rollout is judged a failure after twelve months. What distinguishes a recoverable failure from a terminal one?', '[{"id":"a","text":"Whether the organisation learned why it failed"},{"id":"b","text":"Whether the budget can be extended"},{"id":"c","text":"Whether the vendor remains committed"},{"id":"d","text":"Whether senior sponsorship survived the public setback"}]'::jsonb, 'a', 'A failure that produced a clear diagnosis is an investment. One that produced only disappointment leaves the next attempt no better positioned.', true, 'approved'),
  ('AC-21', 'adoption_change', 'medium', 'You must communicate an AI programme that will change some roles. What best preserves trust?', '[{"id":"a","text":"Confirm that no roles will be affected"},{"id":"b","text":"Delay all communication until the plans have been finalised"},{"id":"c","text":"Say what is known, what is not, and when you will update"},{"id":"d","text":"Focus the message on the technology benefits"}]'::jsonb, 'c', 'People can work with uncertainty; they cannot work with silence, or with reassurance that later proves false. Naming the unknowns makes the knowns believable.', true, 'approved'),
  ('AC-22', 'adoption_change', 'medium', 'Middle managers are the main blockage in your AI rollout. What most often explains this?', '[{"id":"a","text":"They have received the least technical training of any group"},{"id":"b","text":"They are closest to retirement"},{"id":"c","text":"They are measured on delivery the change disrupts"},{"id":"d","text":"They receive the least communication"}]'::jsonb, 'c', 'Middle managers absorb the short-term cost of change while being held to unchanged targets. Adjusting what they are measured on moves more than persuasion does.', true, 'approved'),
  ('AC-23', 'adoption_change', 'hard', 'You must choose between deep AI adoption in one function and shallow adoption everywhere. What should decide it?', '[{"id":"a","text":"Whichever approach produces the larger headline number"},{"id":"b","text":"Whether you currently need proof or need breadth"},{"id":"c","text":"Deep adoption is always the stronger choice"},{"id":"d","text":"Whichever option the executive team prefers"}]'::jsonb, 'b', 'Both are defensible strategies for different problems. Depth produces a credible case study; breadth builds baseline fluency. The choice depends on which you lack.', true, 'approved'),
  ('AC-24', 'adoption_change', 'hard', 'AI capability is now widespread in your organisation, but decisions are made no faster. What is the most likely structural cause?', '[{"id":"a","text":"The tools are not yet capable enough"},{"id":"b","text":"Governance and approval paths never changed"},{"id":"c","text":"Staff still lack confidence in the outputs"},{"id":"d","text":"Data quality across the organisation remains insufficient"}]'::jsonb, 'b', 'Analysis speed was rarely the constraint on decisions. If approval routes, meeting cycles and sign-off rights are unchanged, faster inputs simply queue earlier.', true, 'approved')
on conflict (code) do update set
  pillar            = excluded.pillar,
  difficulty        = excluded.difficulty,
  question_text     = excluded.question_text,
  options           = excluded.options,
  correct_option_id = excluded.correct_option_id,
  explanation       = excluded.explanation,
  active            = excluded.active,
  review_status     = excluded.review_status;
